name: Deploy Vue to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21' # Node.js 버전을 프로젝트에 맞게 설정하세요.

      - name: Install dependencies
        run: npm install

      - name: Build Vue project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # S3 버킷의 리전으로 변경

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://my-vue-project --delete
